import { getUnifiedApiBySlug } from '@/lib/apiMarketplaceData';

function buildDefaultData(slug: string, body: unknown, query: Record<string, string>) {
  return {
    slug,
    message: `Sandbox fixture for ${slug} generated by APIverse.`,
    echoedQuery: query,
    echoedBody: body ?? null,
  };
}

function tryParseFixture(raw: string) {
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return {
      raw,
    };
  }
}

export function buildSandboxFixtureResponse({
  slug,
  body,
  query,
  requestId,
}: {
  slug: string;
  body: unknown;
  query: Record<string, string>;
  requestId: string;
}) {
  const unified = getUnifiedApiBySlug(slug);
  const apiName = unified?.catalog.product ?? slug;
  const provider = unified?.catalog.provider ?? 'APIverse';
  const sampleFixture = unified?.detail.sampleResponse ? tryParseFixture(unified.detail.sampleResponse) : null;

  let data: Record<string, unknown>;

  switch (slug) {
    case 'openai-responses':
      data = {
        ...(sampleFixture ?? {}),
        fixture_id: `fixture_${requestId.slice(0, 10)}`,
        mode: 'sandbox_fixture',
      };
      break;
    case 'stripe-payments':
      data = {
        ...(sampleFixture ?? {}),
        amount: typeof body === 'object' && body && 'amount' in (body as Record<string, unknown>) ? (body as Record<string, unknown>).amount : 4999,
        currency: typeof body === 'object' && body && 'currency' in (body as Record<string, unknown>) ? (body as Record<string, unknown>).currency : 'usd',
        mode: 'sandbox_fixture',
      };
      break;
    case 'google-maps-places':
      data = {
        ...(sampleFixture ?? {}),
        mode: 'sandbox_fixture',
      };
      break;
    case 'sarvam-indic-ai':
      data = {
        ...(sampleFixture ?? {}),
        mode: 'sandbox_fixture',
      };
      break;
    default:
      data = sampleFixture ?? buildDefaultData(slug, body, query);
      break;
  }

  return {
    success: true,
    request_id: requestId,
    api: {
      slug,
      name: apiName,
    },
    data,
    meta: {
      tracked_by: 'APIverse',
      docs_path: `/api-marketplace/${slug}`,
      provider_reference: provider,
      environment_mode: 'sandbox_fixture',
      note: 'This is a sandbox fixture response owned by APIverse. It does not call the upstream provider directly.',
      echoed_query: query,
      echoed_body: body ?? null,
      generated_at: new Date().toISOString(),
    },
  };
}
